domain: cavenderbi.github.io/blog
url: https://cavenderbi.github.io/blog
title: CS-4100 Blog | Brandan Cavender
description: A blog for CS-4100, and possibly more, written to and maintained by your's truely. 